Loading parflow-ml/latest
  Loading requirement: openmpi/gcc/4.1.0 parflow/3.9.0 gdal/3.2.1
(0.001, 1e-08)
/scratch/taylor/ensembles_sbi/02_PARFLOW_OUT/02_PARFLOW_OUT/0819_01_K-0.001-M-1e-08-_1995
Traceback (most recent call last):
  File "storage.py", line 93, in <module>
    run = Run.from_definition(path_PFdatabase)
  File "/home/SHARED/software/anaconda3/2020.07e/lib/python3.8/site-packages/parflow/tools/core.py", line 276, in from_definition
    new_run.pfset(silence_if_undefined=True, **kwargs)
  File "/home/SHARED/software/anaconda3/2020.07e/lib/python3.8/site-packages/parflow/tools/database/core.py", line 601, in pfset
    flat_map = read_pfidb(pfidb_file)
  File "/home/SHARED/software/anaconda3/2020.07e/lib/python3.8/site-packages/parflow/tools/io.py", line 331, in read_pfidb
    with open(full_path, 'r') as input_file:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/taylor/ensembles_sbi/02_PARFLOW_OUT/02_PARFLOW_OUT/0819_01_K-0.001-M-1e-08-_1995/Taylor_1995.pfidb'
